image: node:10.15.0
pipelines:
  default:
    - step:
        caches:
          - composer        
        script:
          - pipe: atlassian/scp-deploy:1.5.0
            variables:
              USER: 'jobportal'
              SERVER: '20.198.9.131'
              REMOTE_PATH: '/home/jobportal/'
              LOCAL_PATH: '${BITBUCKET_CLONE_DIR}'
          - pipe: atlassian/ssh-run:0.8.0
            variables:
              SSH_USER: 'jobportal'
              SERVER: '20.198.9.131'
              MODE: 'command'
              COMMAND: 'sh /home/jobportal/build/jobportal-backend-deploy.sh'