import 'dotenv/config'

export const imapConfig = {
   
    auth: {
    user: process.env.NODEMAILER_USER, ////1290--pin
    pass: process.env.NODEMAILER_PASS,  //pass key generated by app pas
   },
    host: 'imap.gmail.com',
    port: 993, // IMAPS port
    secure:true
  
  }
